# Generated by Django 4.0 on 2023-10-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='updated_at',
        ),
    ]
