# Generated by Django 4.0 on 2023-10-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_rename_updated_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
